POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Blockchain Developer Roadmap",
    "author": "Mary Jane",
    "url": "https://roadmap.sh/blockchain",
    "likes": 60
}