POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImhhcnJ5IiwiaWQiOiI2NDk4ZThlNjY1NjJhYmM5NzkwYTdhMzIiLCJpYXQiOjE2ODc3NTMzMTl9.i4NxJo19we_-8iedS4ug6Dysdwxzx17P_T89NeVn5Qw

{
    "title": "Go Developer Roadmap",
    "author": "Phil Jones",
    "url": "https://roadmap.sh/golang",
    "likes": 10
}